//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Driver()
        {
            this.Passage = new HashSet<Passage>();
        }
    
        public int tabNum { get; set; }
        public string name { get; set; }
        public System.DateTime dateOfStartWork { get; set; }
        public int idCategory { get; set; }
        public decimal troubleFreeExp { get; set; }
        public string categoryName { get
            {
                if (this != null)
                    return this.CategoryOfDriver.Title;
                else return "";
            } }

        public string Experiense { get
            {
                int days = (DateTime.Now - dateOfStartWork).Days;
                int years = days / 30 / 12;
                int month = days / 30 - years * 12;
                if (month == 0)
                    return years + " лет";
                else
                    return years + " лет " + month + " мес.";
            } }
        public virtual CategoryOfDriver CategoryOfDriver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passage> Passage { get; set; }
    }
}
