//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainDataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrainEntities : DbContext
    {
        public TrainEntities()
            : base("name=TrainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryOfDriver> CategoryOfDriver { get; set; }
        public virtual DbSet<Driver> Driver { get; set; }
        public virtual DbSet<Passage> Passage { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<StateTrain> StateTrain { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Train> Train { get; set; }
        public virtual DbSet<TypeTrain> TypeTrain { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
