//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Train
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Train()
        {
            this.Passage = new HashSet<Passage>();
        }
    
        public int number { get; set; }
        public int typeId { get; set; }
        public int stateID { get; set; }
        public int timeWork { get; set; }

        public string State { get { return StateTrain.Titile; } }
        public string Type { get { return TypeTrain.Title; } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passage> Passage { get; set; }
        public virtual StateTrain StateTrain { get; set; }
        public virtual TypeTrain TypeTrain { get; set; }
    }
}
